spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:ticket_reservation_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create # ?????? ?? ??? ???? ???? ?????.
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ??????.
        show_sql: true   # ???? SQL ??? ??? ?????.
    defer-datasource-initialization: true