spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:ticket_reservation_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  # Redis ?? ??
  data:
    redis:
      host: localhost
      port: 6379

# Admin Token (?? ?????? ???? ??? ???? ???)
admin:
  token: AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC

# JWT Secret Key (??? ???? ? ???? ???? ?????)
jwt:
  secret:
    key: 7ZWt7KO87IS47JqU66eI7J207YSw6rCV7Z2s7IKs7YyM66W07J24Li4=
